######################################################################
# Automatically generated by qmake (2.01a) to 28. sep 16:43:38 2006
######################################################################

TEMPLATE = app
TARGET = sdi
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += sdiwindow.h
SOURCES += main.cpp sdiwindow.cpp
RESOURCES += images.qrc

TRANSLATIONS += sdi_zh_CN.ts

QMAKE_CXXFLAGS += -std=c++11

QT += widgets
